spring:
  # redis 配置
  redis:
    host: 121.43.113.221
    port: 6379
    password: xiezeyi
    database: 5
    # jedis 连接池配置
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: 1000
#        lettuce 连接池配置
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000