server:
  port: 80

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开配配置注册中心进行路由功能
          lower-case-service-id: true #将服务名称转小写
      routes:
        - id: ms-diners
          uri: lb://ms-diners
          predicates:
            - Path=/hello/**
# 配置 Eureka Server 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  # 在注册中心注册时候通过ip地址来注册
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
